WhisperApp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("audiofileconversion/", include("audiofileconversion.urls")),
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

audiofileconversion/urls.py
from django.urls import path
from . import views

app_name = "audiofileconversion"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

audiofileconversion/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text
    
    @admin.display(
            boolean=True,
            ordering="pub_date",
            description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

 


# Create your models here.

audiofileconversion/views.py
from django.http import HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = "audiofileconversion/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """ Return the last five published questions. """
        return Question.objects.order_by("pub_date")[:5]
    
class DetailView(generic.DetailView):
    model = Question
    template_name = "audiofileconversion/detail.html"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = "audiofileconversion/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except(KeyError, Choice.DoesNotExist):
        return render(
            request,
            "audiofileconversion/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("audiofileconversion:results", args=(question.id,)))
    
def get_queryset(self):
    return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]

audiofileconversion/templates/audiofileconversion/detail.html
<form action="{% url 'audiofileconversion:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
  <legend><h1> {{ question.question_text }} </h1></legend>
  {% if error_messeage %}<p><strong>{{ error_message }}</strong></p>{% endif %}
  {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choise{{ forloop.counter }}" value={{ choice.id }}>
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
<br>
  {% endfor %}
</fieldset>
<input type="submit" value="vote">
</form>

audiofileconversion/templates/audiofileconversion/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'audiofileconversion/style.css' %}">

{% if  latest_question_list %}
  <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'audiofileconversion:detail' question.id %}"> {{ question.question_text }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>No audiofileconversion are avilable.</p>
{% endif %}

audiofileconversion/templates/audiofileconversion/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
  <li>{{ choice.choice_text }} -- {{ choice.votes }}vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'audiofileconversion:detail' question.id %}">Vote again?</a>